# Generated by Django 3.2.3 on 2021-10-03 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
